import React from 'react';
import {Line} from 'react-chartjs-2';

const YieldLine = (props) => {
    const data = {
        labels: props.timeArr,
        datasets: [
          {
            label: "5 Year",
            fill: false,
            lineTension: 0.5,
            backgroundColor: 'rgba(75,192,192,0.4)',
            borderColor: 'rgba(75,192,192,1)',
            borderCapStyle: 'butt',
            borderDash: [],
            borderDashOffset: 0.0,
            borderJoinStyle: 'miter',
            pointBorderColor: 'rgba(75,192,192,1)',
            pointBackgroundColor: '#fff',
            pointBorderWidth: 1,
            pointHoverRadius: 5,
            pointHoverBackgroundColor: 'rgba(75,192,192,1)',
            pointHoverBorderColor: 'rgba(220,220,220,1)',
            pointHoverBorderWidth: 2,
            pointRadius: 1,
            pointHitRadius: 10,
            data: props.fiveArr,
          },
          {
            label: "7 Year",
            fill: false,
            lineTension: 0.5,
            backgroundColor: 'rgba(75,145,192,0.4)',
            borderColor: 'rgba(75,145,192,0.5)',
            borderCapStyle: 'butt',
            borderDash: [],
            borderDashOffset: 0.0,
            borderJoinStyle: 'miter',
            pointBorderColor: 'rgba(75,145,192,0.4)',
            pointBackgroundColor: 'rgba(75,145,192,0.4)',
            pointBorderWidth: 1,
            pointHoverRadius: 5,
            pointHoverBackgroundColor: 'rgba(75,145,192,0.4)', //Hover pointer color
            pointHoverBorderColor: 'rgba(75,145,192,0.4)',
            pointHoverBorderWidth: 2,
            pointRadius: 1,
            pointHitRadius: 10,
            data: props.sevenArr,
          },
          {
            label: "10 Year",
            fill: false,
            lineTension: 0.5,
            backgroundColor: 'rgba(34,14,243,0.4)',
            borderColor: 'rgba(34,14,243,0.5)',
            borderCapStyle: 'butt',
            borderDash: [],
            borderDashOffset: 0.0,
            borderJoinStyle: 'miter',
            pointBorderColor: 'rgba(34,14,243,0.4)',
            pointBackgroundColor: 'rgba(34,14,243,0.4)',
            pointBorderWidth: 1,
            pointHoverRadius: 5,
            pointHoverBackgroundColor: 'rgba(34,14,243,0.4)',
            pointHoverBorderColor: 'rgba(34,14,243,0.4)',
            pointHoverBorderWidth: 2,
            pointRadius: 1,
            pointHitRadius: 10,
            data: props.tenArr,
          },
          {
            label: "20 Year",
            fill: false,
            lineTension: 0.5,
            backgroundColor: 'rgba(77,65,220,0.4)',
            borderColor: 'rgba(77,65,220,0.5)',
            borderCapStyle: 'butt',
            borderDash: [],
            borderDashOffset: 0.0,
            borderJoinStyle: 'miter',
            pointBorderColor: 'rgba(77,65,220,0.4)',
            pointBackgroundColor: 'rgba(77,65,220,0.4)',
            pointBorderWidth: 1,
            pointHoverRadius: 5,
            pointHoverBackgroundColor: 'rgba(77,65,220,0.4)',
            pointHoverBorderColor: 'rgba(77,65,220,0.4)',
            pointHoverBorderWidth: 2,
            pointRadius: 1,
            pointHitRadius: 10,
            data: props.twentyArr,
          },
          {
            label: "30 Year",
            fill: false,
            lineTension: 0.5,
            backgroundColor: 'rgba(107,75,150,0.4)',
            borderColor: 'rgba(107,75,150,0.5)',
            borderCapStyle: 'butt',
            borderDash: [],
            borderDashOffset: 0.0,
            borderJoinStyle: 'miter',
            pointBorderColor: 'rgba(107,75,150,0.4)',
            pointBackgroundColor: 'rgba(107,75,150,0.4)',
            pointBorderWidth: 1,
            pointHoverRadius: 5,
            pointHoverBackgroundColor: 'rgba(107,75,150,0.4)',
            pointHoverBorderColor: 'rgba(107,75,150,0.4)',
            pointHoverBorderWidth: 2,
            pointRadius: 1,
            pointHitRadius: 10,
            data: props.thirtyArr,
          },
        ]
      };
      return(
        <div>
          <Line data={data} />
        </div>
      )
}

export default YieldLine;